version: "3"

services:
  flow:
    image: totalplatform/flow:latest
    restart: always
    ports:
      - 172.17.0.1:6433:8000
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
